Add minor version number to Cargo.toml
Newer versions of cargo require a minor version number and refuse to compile without it, giving an error:

```
error: failed to parse manifest at `/home/nom/Workspaces/sway.workspace/rustofi/Cargo.toml`

Caused by:
  unexpected end of input while parsing minor version number for key `package.version`
```